// Writes qr.js: the QR code of the link the film closes on, as rows of 0/1, drawn by the film itself.
// node tools/qr.mjs [url]
import QR from 'qrcode';
import {writeFileSync} from 'node:fs';
import path from 'node:path';
const dir = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const URL_ = process.argv[2] || 'https://t.me/ibkdarslik_bot';                // the guide's Telegram bot
const q = QR.create(URL_, {errorCorrectionLevel: 'M'}), n = q.modules.size, rows = [];
for (let y = 0; y < n; y++) { let r = ''; for (let x = 0; x < n; x++) r += q.modules.get(x, y) ? '1' : '0'; rows.push(r); }
writeFileSync(path.join(dir, 'qr.js'), `// QR code of ${URL_} (error correction M), generated by tools/qr.mjs\n'use strict';\nconst QR_URL = ${JSON.stringify(URL_)};\nconst QR_ROWS = ${JSON.stringify(rows)};\n`);
console.log(`qr.js: ${n}x${n}`);
